project:
  type: website

website:
  title: "Tom Saunders"
  description: ""
  # favicon:
  page-navigation: true
  back-to-top-navigation: true
  # comments: 
  #   utterances: 
  #     repo: tesaunders/tomsaunders 
  #     label: utterances
  #     theme: body-light
  #     issue-term: title
  
  # navbar:
  #   title: "Tom Saunders"
  #   right:
  #     - text: Blog
  #       href: blog.qmd
  #     - text: Publications
  #       href: publications.qmd
  #     - text: Projects
  #       href: projects.qmd

  page-footer:
    border: true
    left: |
      Powered by [{{< iconify simple-icons:quarto >}} Quarto](https://quarto.org).
    center: |
      &copy; Tom Saunders 
      [{{< iconify academicons:orcid >}}](https://orcid.org/0000-0003-1780-0314)
      [{{< iconify fa6-brands:bluesky >}}](https://bsky.app/profile/tomsaunders.me)
      [{{< iconify fa:github >}}](https://github.com/tesaunders)

format:
  html:
    theme: darkly
    css: styles.css
    code-link: true
    pagetitle: "{{< meta title >}}"

execute:
  freeze: auto